# Generated by Django 3.1.4 on 2021-01-03 20:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCocktails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail_name', models.CharField(max_length=100, null=True)),
                ('cocktails_category', models.CharField(choices=[('alc', 'Alcoholic'), ('nonalc', 'Noc-Alcoholic')], max_length=50)),
                ('crockery_category', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=50)),
                ('method_category', models.CharField(choices=[('stir', 'Stirren'), ('shake', 'Shaken'), ('build', 'Build')], max_length=50)),
                ('ingredients', models.TextField(max_length=100, null=True)),
                ('execution', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='cocktails_pics')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
